/* SFX FROM THE DOS ORIGINAL - generated by tools/dos_sfx_convert.py. Do
   NOT edit by hand, run the tool again instead. On the PC, Xenon 2 uses no
   sampler but David Whittaker's PC SPEAKER driver - square wave, exactly
   like our T6W28. What carries over is the pitch: PIT f = 1193182/d, T6W28
   f = 96000/n, so n = d * 0.080457. Start and end period sit as word 1 and
   2 in the 15-byte records at DRV:0x420 (file 0x157B0). Duration and
   attenuation are SET, not read from the record - the remaining record
   fields cannot be read reliably without a disassembly of the tone
   generator. Details: tools/dos_sfx_convert.py. !! NO SfxPreset TABLE:
   cc900 is C89, and the designated initialisers (.tone = {...}) that
   sounds.h shows in a comment are C99 - the compiler answers with "Too
   many initializers". Hence a switch with direct calls; as a side effect
   that saves the table in ROM. */
#ifndef SFX_ORIG_H
#define SFX_ORIG_H

#define SFX_SHOT        0   /* player shot */
#define SFX_EXPLOSION   1   /* explosion / death */
#define SFX_SMARTBOMB   2   /* smart bomb */
#define SFX_FLAMER      3   /* flamer */
#define SFX_LASER       4   /* laser */
#define SFX_LASERHIT    5   /* laser sweep */
#define SFX_ENERGY      6   /* energy pickup */
#define SFX_WEAPON      7   /* weapon installed */
#define SFX_DIVE        8   /* dive */
#define SFX_SHOPDOOR    9   /* shop: doors */
#define SFX_SHOPCUR    10   /* shop: cursor */
#define SFX_SHOPBUY    11   /* shop: purchase */

static void sfx_orig_play(u8 id)
{
    switch (id) {
    case SFX_SHOT:      /* 0x02 player shot, 86 Hz -> 202 Hz; 1 octave(s) higher, the T6W28 does not go lower */
        /* Attenuation 4 -> 1: measured, the shot sat 11.3 dB below the
           music and was practically gone in the arrangement (user report).
           The scale is 2 dB per step, so three steps are +6 dB = twice the
           loudness. The attenuation is SET anyway, not read from the DOS
           record - only the frequencies (word 1/2) are documented there,
           see the header. */
        Sfx_PlayToneEx(0u, 560u, 1u, 8u, 476u, -10, 1u, 0u, 1u, 1u, 1u, 2u); break;
    case SFX_EXPLOSION: /* 0x06 explosion / death, 159 Hz -> noise */
        Sfx_PlayNoiseEx(2u, 0u, 2u, 18u, 0u, 0u, 1u, 1u, 3u); break;
    case SFX_SMARTBOMB: /* 0x0B smart bomb, 143 Hz -> noise */
        Sfx_PlayNoiseEx(2u, 0u, 2u, 24u, 0u, 0u, 1u, 1u, 3u); break;
    case SFX_FLAMER:    /* 0x05 flamer, 86 Hz; 1 octave(s) higher, the T6W28 does not go lower */
        Sfx_PlayToneEx(0u, 560u, 1u, 10u, 560u, 0, 1u, 0u, 0u, 1u, 1u, 2u); break;
    case SFX_LASER:     /* 0x10 laser, 47 Hz -> 86 Hz; 2 octave(s) higher, the T6W28 does not go lower */
        Sfx_PlayToneEx(0u, 515u, 1u, 10u, 560u, 4, 1u, 0u, 1u, 1u, 1u, 2u); break;
    case SFX_LASERHIT:  /* 0x15 laser sweep, 373 Hz */
        Sfx_PlayToneEx(1u, 257u, 1u, 6u, 257u, 0, 1u, 0u, 0u, 1u, 1u, 2u); break;
    case SFX_ENERGY:    /* 0x12 energy pickup, 104 Hz */
        Sfx_PlayToneEx(1u, 927u, 1u, 14u, 927u, 0, 1u, 0u, 0u, 1u, 1u, 2u); break;
    case SFX_WEAPON:    /* 0x04 weapon installed, 533 Hz */
        Sfx_PlayToneEx(1u, 180u, 1u, 14u, 180u, 0, 1u, 0u, 0u, 1u, 1u, 2u); break;
    case SFX_DIVE:      /* 0x18 dive, 104 Hz; end value in the record implausible (8), therefore constant */
        Sfx_PlayToneEx(0u, 927u, 1u, 14u, 927u, 0, 1u, 0u, 0u, 1u, 1u, 2u); break;
    case SFX_SHOPDOOR:  /* 0x07 shop: doors, 99 Hz */
        Sfx_PlayToneEx(2u, 965u, 1u, 22u, 965u, 0, 1u, 0u, 0u, 1u, 1u, 2u); break;
    case SFX_SHOPCUR:   /* 0x08 shop: cursor, 75 Hz -> 50 Hz; 1 octave(s) higher, the T6W28 does not go lower */
        Sfx_PlayToneEx(1u, 644u, 1u, 4u, 965u, 80, 1u, 0u, 1u, 1u, 1u, 2u); break;
    case SFX_SHOPBUY:   /* 0x09 shop: purchase, 1065 Hz */
        Sfx_PlayToneEx(1u, 90u, 1u, 9u, 90u, 0, 1u, 0u, 0u, 1u, 1u, 2u); break;
    default: break;
    }
}

#endif
